#!/home/z/zhouyh/anaconda3/envs/OUTPOST/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from antismash.download_databases import _main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(_main())
